# Generated by Django 4.2.6 on 2023-10-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='accounts/', verbose_name='Файл с кредами')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Активен ли аккаунт')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название на русском')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название на английском')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название на русском')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название на английском')),
                ('description_ru', models.TextField(verbose_name='Описание на русском')),
                ('description_en', models.TextField(verbose_name='Описание на английском')),
                ('price', models.FloatField(verbose_name='Цена в $')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(verbose_name='TG id')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя')),
                ('selected_language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='ru', max_length=100, verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('user_in_checking', 'Пользователь проверяет'), ('ok', 'Аккаунт валиден'), ('not_ok', 'Аккаунт невалиден'), ('admin_in_checking', 'Админ проверяет на валидность'), ('canceled', 'Заявка отклонена')], default='user_in_checking', max_length=100, verbose_name='Статус')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='datacenter.account', verbose_name='Продаваемый аккаунт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='datacenter.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='datacenter.product', verbose_name='К какому товару привязан'),
        ),
    ]
