# Generated by Django 4.2.6 on 2023-10-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_check', models.IntegerField(verbose_name='Время проверки аккаунта в минутах')),
                ('_singleton', models.BooleanField(default=True, editable=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
