# Generated by Django 4.2.2 on 2023-10-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0005_product_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Кол-во $'),
        ),
    ]
